---
- src: geerlingguy.pip
- src: geerlingguy.ruby
- src: geerlingguy.docker
- src: geerlingguy.packer
- src: geerlingguy.nginx
- src: secfigo.terraform
# - src: geerlingguy.elasticsearch
# - src: geerlingguy.kibana
# - src: geerlingguy.logstash
# - src: secfigo.gauntlt
