---

- name: Setup production environment
  hosts: all
  become: true
  become_user: root
  remote_user: vagrant
  vars:
    # Docker settings for runner
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: "present"

    # Docker compose
    docker_install_compose: true
    docker_compose_version: "v2.11.0"
    docker_compose_path: /usr/local/bin/docker-compose

    docker_apt_release_channel: stable
    docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

    # host entries won't work in docker
    # see https://stackoverflow.com/questions/28327458/how-to-add-my-containers-hostname-to-etc-hosts
    add_host_entries: true

  roles:
    - common
    - geerlingguy.docker
    - prod
  tags:
    - prod
